.eslintignore
.eslintrc.yml
.gitattributes
app.js
package-lock.json
package.json

剛設置好，
可能要請你確認這樣子有沒有正確的套用到你的環境，
感謝。

設置ESLint環境

---

.eslintignore
migrations/20190115071418-create-followship.js
migrations/20190115071419-create-like.js
migrations/20190115071420-create-reply.js
migrations/20190115071420-create-tweet.js
migrations/20190115071421-create-user.js
models/like.js
models/reply.js
models/tweet.js
models/user.js
seeders/20230319034154-user-seed-file.js
seeders/20230319041929-tweet-seed-file.js
seeders/20230319043444-reply-seed-file.js

錯誤修正:
1. DB column還是改成created_at..etc等底線的名稱, 因為撈資料時他是用底線的去撈, 直接叫createdAt, 就會找不到created_at的欄位導致錯誤
2. Like model的關聯修正

fix: fix model relationship setting and column update

---

app.js
controllers/tweet-controller.js
middleware/error-handler.js
routes/index.js
routes/modules/tweet.js
services/tweet-services.js

基本的routes都設定好了:
在routes/index.js裡目前是這樣設計
router.use('/tweets', tweet)
後續可能就是由各自補上各自的路由
router.use('/users', user)
router.use('/admin', admin)

feat: add routes setting and error handler and get tweets

---

.eslintrc.yml
controllers/tweet-controller.js
routes/index.js
routes/modules/tweet.js
services/tweet-services.js

功能:
1. 新增瀏覽所有推文且按照時間排序
2. 瀏覽單一推文包含回覆串
3. 瀏覽單一推文的回覆串
4. 回覆一則推文
5. 喜歡與取消喜歡一則推文

feat: add Tweet & Reply & Like related create & read fuctions

---

controllers/user-controller.js
routes/modules/user.js
services/user-services.js

能查看使用者喜歡的推文，
剛傳出空值以為我又哪裡沒寫好，
原來是like 裡面沒有資料呀。

feat: add getLikeTweet route

---

seeders/20230319041929-tweet-seed-file.js
seeders/20230319043444-reply-seed-file.js
seeders/20230322061810-like-seed-file.js
seeders/20230322064133-follow-seed-file.js

功能:
更新種子資料
-增加followship與like種子
-推文與likes與replies加入時間差

feat: update Seed files

---

.gitignore
helpers/file-helpers.js
middleware/multer.js
routes/modules/user.js
services/user-services.js

功能
新增multer與file helper
修改putUser services
這邊圖片名稱是Avatar以及Cover

Photo feature

---

Procfile
config/config.json

 feat: update file to deploy to heroku

---

app.js

fix: port update

---

services/tweet-services.js
services/user-services.js

fix: fix some bugs

---

controllers/user-controller.js
routes/index.js
services/user-services.js

目前修好其他錯誤，
修改註冊路徑名稱，與測試檔不符，
其他大概都是資料的傳出去不能多一層{}是要Array，
剩下getUsersFollowings/Followers 的多層巢狀結構讓他無法拿到資料，
這個我只能換個寫法才能解決，
先繳交好的部分。

fix : pass test 5

---

models/followship.js

fix: fix followship model

---

services/tweet-services.js

修正
因為有些services沒有先確認tweet存不存在, 因此補上這個確認機制

fix: update services for checking tweet exist

---

package.json
services/tweet-services.js

我修正好package json的指令了
現在可以使用npm run start or npm run dev指令

Fix package json

---

services/user-services.js

fix: fix null column check for putUser

---

config/passport.js

fix: update JWT in passport

---

README.md
controllers/admin-controller.js

因為目前跑不到status200，然後他要的資料格式是json所以我改這樣看看可不可以，本地測試OK!

fix: fix one

---

app.js

fix: remove options

---

services/tweet-services.js

feat: update getTweet with counts props

---

services/tweet-services.js

feat: update get one tweet

---

services/user-services.js

feat: delete console.log and annotation

---

services/user-services.js

新增回覆頁面當前使用者資訊，
內容包括 : id、account、name、avatar，
使其抓資料不用額外抓。

feat: add getRepliedTweets user model

---

services/admin-services.js

feat: add admin getTweets's user information

---

services/tweet-services.js

feat: add User info in getTweets
